-- escribe una consulta que liste *exclusivamente* el nombre de las canciones de una playlist concreta, 
-- con el nombre de su género y el nombre de tipo de medio
-- Si tienes muchos resultados, puedes añadir LIMIT X al final de la consulta, donde X es el número de filas que se devuelven